isde-project group E
unica-isde/isde-projects-2023-E pull request #5
Opened 2024-03-23 15:29 UTC by G-P-x

2024-04-08 12:57 UTC, asotgiu commented on .vscode/c_cpp_properties.json
Why is this file versioned?

2024-04-08 12:57 UTC, asotgiu commented on .vscode/launch.json
Why is this file versioned?

2024-04-08 12:58 UTC, asotgiu commented on .vscode/settings.json
Why is this file versioned?

2024-04-08 13:03 UTC, asotgiu commented on app/ml/image_transformation.py
> +        sharped_image.save(output_image_path, format="JPEG")  # create a sharped copy of the original image
What happens if multiple users ask for the same job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-04-08 13:08 UTC, asotgiu commented on app/ml/image_uploader.py
> +        f.write(contents)
What happens if multiple users ask for the same job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-04-08 13:11 UTC, asotgiu commented on main.py
> +        json.dump(result.classification_results, f)  #write the result into the JSON file
What happens if multiple users ask for a classification job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-04-08 13:11 UTC, asotgiu commented on main.py
> +    plt.savefig('plot.png')
What happens if multiple users ask for a classification job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-04-08 13:16 UTC, asotgiu commented on main.py
> +    classification_scores = classify_image(model_id=model_id, img_id=image_id)
If something goes wrong (for instance, an invalid file is uploaded), the app crashes and the file remains in memory anyway. The error should be handled (for instance with a try-except) and the file should be removed. Moreover, the user does not know what happened as no specific error message is shown in the web interface.

2024-04-08 13:17 UTC, asotgiu commented on plot.png
Why is this file versioned?

2024-04-08 13:17 UTC, asotgiu commented on result.json
Why is this file versioned?

2024-04-08 13:28 UTC, asotgiu requested changes
I reviewed the code and tested the app. Most of the requested functionalities are implemented, but there are some issues to solve before accepting the Pull Request.
Please fix them and request a new review when it's done. There's no need to open a new PR, it's enough to push the new commits to the origin repository (yours) of the PR. In that way, I will see only the new changes and I won't have to review the full code again.
- Issue #2 required to modify image color, brightness, contrast, and sharpness. However, only the latter is implemented. Please, add the other transformations.
- Remove files that should not be versioned, or provide an explanation on why the file is there (perhaps they should just be added to the .gitignore).
- Fix the concurrency problem with the results, the plots, and the uploaded images being stored with the same name, and handle the uploading of invalid images.
- Improve the documentation through the code and add a changelog with the list of resolved issues to the pull request documentation (edit the description of the PR, or at least use the GUI functionality to link the PR to the issues of the target repository).

Thanks!

2024-05-21 09:06 UTC, G-P-x commented
We encountered issues with merging the various branches. The release working tree became completely messed up, and we had to restore the work by starting over from the beginning. This time, we tried to follow the instructions given in the previous review, adding a changelog with the various modifications made compared to the initial project.

2024-05-23 14:09 UTC, asotgiu requested changes
I rewieved again the entire code, and now all the requested functionalities are implemented.
The documentation was improved, and a changelog was added.
Image transformation looks good now, and all files that didn't require to be versioned were removed.
The concurrency problem has been solved for the results and the plot to be downloaded, but it still remains for the uploaded and transformed images.
In these two cases, you always save an image in the same file using hardcoded paths (`uploaded_image.JPEG` and `transformed_image.JPEG`, respectively). Imagine what could happen if two users upload an image nearly simultaneously. The first uploaded image might be deleted or overwritten by the second one, and both users might receive the results related to the second image (or an error). The same could happen when applying transformations to an image.
Please fix this issue to get the PR merged. I can suggest two solutions, but you are free to implement a different one:
- store images with a unique file name for each user;
- avoid storing images at all, reusing them immediately.
If you need further help, please contact us by email.
Thank you!

2024-06-07 15:27 UTC, G-P-x commented
We solved the concurrency problem using the uuid library, It should be ok now

2024-06-10 08:54 UTC, asotgiu approved these changes
Well done, I merge the PR

2024-06-10 08:55 UTC, merged